# Generated by Django 6.0.5 on 2026-06-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Remote', max_length=100),
        ),
    ]
